# Generated by Django 2.2.3 on 2019-07-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
